"""add transaction duplicate detection

Revision ID: 3a80ae28526e
Revises: 86a5e0b5bea2
Create Date: 2026-08-09 18:00:16.404416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a80ae28526e'
down_revision: Union[str, Sequence[str], None] = '86a5e0b5bea2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('duplicate_of_transaction_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_transactions_duplicate_of_transaction_id'), 'transactions', ['duplicate_of_transaction_id'], unique=False)
    op.create_foreign_key(None, 'transactions', 'transactions', ['duplicate_of_transaction_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_index(op.f('ix_transactions_duplicate_of_transaction_id'), table_name='transactions')
    op.drop_column('transactions', 'duplicate_of_transaction_id')
    # ### end Alembic commands ###
