"""add blacklisted_senders

Revision ID: 86a5e0b5bea2
Revises: 4e0e7e4c609a
Create Date: 2026-08-09 13:50:15.417047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86a5e0b5bea2'
down_revision: Union[str, Sequence[str], None] = '4e0e7e4c609a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blacklisted_senders',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('sender', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'sender', name='uq_blacklisted_senders_user_sender')
    )
    op.create_index(op.f('ix_blacklisted_senders_user_id'), 'blacklisted_senders', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blacklisted_senders_user_id'), table_name='blacklisted_senders')
    op.drop_table('blacklisted_senders')
    # ### end Alembic commands ###
